name: Publish Package to npmjs

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
  
      - name: Prepare build environment
        id: prepare
        uses: ./.github/actions/prepare-environment
        with:
          node-version: 18.x
          use-matterbridge-edge: true

      - name: Publish the module
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
