name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    if: github.actor != 'dependabot[bot]'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        use-matterbridge-edge: [true]

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
  
      - name: Prepare build environment
        id: prepare
        uses: ./.github/actions/prepare-environment
        with:
          node-version: ${{ matrix.node-version }}
          use-matterbridge-edge: ${{ matrix.use-matterbridge-edge }} 

      - name: Build the project
        run: npm run build
      
      - name: Run the tests
        run: npm run test
        env:
          ELECTROLUX_API_KEY: ${{ secrets.ELECTROLUX_API_KEY }}
          ELECTROLUX_ACCESS_TOKEN_URL: https://www.thouky.co.uk/api/oauth/electrolux/${{ secrets.ELECTROLUX_API_KEY }}